logging:
  level:
    gestao.service.GeocodeClient: DEBUG

spring:
  application:
    name: gestao-hospital
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/test
      database: test
      